# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/03_APOStrategySarsa.ipynb.
#
# NOTE: This .py was hand-repaired to give the partial-observability SARSA
# agent a working TD error (`RPEioa` + `NextQioa`) and a complete `__init__`
# (learning rates, choice intensity, and `self.TDerror`). The source notebook
# `nbs/Agents/03_APOStrategySarsa.ipynb` should be updated to match before the
# next `nbdev_export`, otherwise these fixes will be overwritten.

# %% auto 0
__all__ = ['stratSARSA']

# %% ../../nbs/Agents/03_APOStrategySarsa.ipynb 2
import numpy as np
import itertools as it
from functools import partial

import jax
from jax import jit
import jax.numpy as jnp

from fastcore.utils import *

from .StrategyBase import strategybase
from .POBase import aPObase   # bugfix: was referenced but never imported
from ..Utils.Helpers import *

# %% ../../nbs/Agents/03_APOStrategySarsa.ipynb 3
class stratSARSA(aPObase, strategybase):
    """
    Class for partially observable CRLD-SARSA agents in strategy (policy) space.

    This is the partial-observability analogue of the full-observability
    `pyCRLD.Agents.StrategySARSA.stratSARSA`. The TD error `RPEioa` mirrors the
    actor-critic `pyCRLD.Agents.POStrategyActorCritic.POstratAC.RPEioa`, but the
    bootstrap term is the SARSA on-policy expected next observation-action value
    (`NextQioa`) instead of the next observation value `NextVioa`. The state-value
    baseline of the actor-critic is replaced by the SARSA `(1/beta) * log(X)`
    baseline (as in the full-observability SARSA agent).
    """

    def __init__(
        self, env, learning_rates, discount_factors, choice_intensities=1, **kwargs
    ):
        """
        Parameters
        ----------
        env : environment object
        learning_rates : the learning rate(s) for the agents
        discount_factors : the discount factor(s) for the agents
        choice_intensities : inverse temperature of softmax / exploitation level
        """
        self.env = env
        Tt = env.T
        assert np.allclose(Tt.sum(-1), 1)
        Rt = env.R
        Ot = env.O
        super().__init__(Tt, Rt, Ot, discount_factors, **kwargs)
        assert np.allclose(env.F, 0), "PO learning w final state not def."

        # learning rates
        self.alpha = make_variable_vector(learning_rates, self.N)

        # intensity of choice
        self.beta = make_variable_vector(choice_intensities, self.N)

        # SARSA temporal-difference error in observation-action (policy) space
        self.TDerror = self.RPEioa

    @partial(jit, static_argnums=(0, 2))
    def RPEioa(
        self, X, norm=False  # Joint policy  # normalize error around actions?
    ) -> jnp.ndarray:  # RP/TD error
        """
        TD error for partially observable policy SARSA dynamics, given joint
        policy `X`.

        Same partial-observability averaging as the actor-critic `RPEioa`, but
        the bootstrap is the SARSA on-policy expected next observation-action
        value `NextQioa` (rather than the next observation value `NextVioa`),
        and the baseline is `(1/beta) * log(X)` (rather than the value `Vio`).
        """
        Bios = self.fast_Bios(X)  # for speed up
        Xisa = self.Xisa(X)  # for speed up

        R = self.Rioa(X, Bios=Bios, Xisa=Xisa)
        NextQ = self.NextQioa(X, Bios=Bios, Xisa=Xisa)

        n = jnp.newaxis
        E = (
            self.pre[:, n, n] * R
            + self.gamma[:, n, n] * NextQ
            - 1 / self.beta[:, n, n] * jnp.log(X)
        )
        E *= self.beta[:, n, n]

        E = E - E.mean(axis=2, keepdims=True) if norm else E
        return E

    @partial(jit, static_argnums=0)
    def NextQioa(
        self, X, Xisa=None, Bios=None, Qioa=None, Tioo=None, Rio=None, Rioa=None
    ) -> jnp.ndarray:  # Next state-action values
        """
        Policy-average SARSA next observation-action value for agent i, current
        observation o and action a.

        Analogous to the actor-critic `NextVioa`, but bootstraps on the on-policy
        expected next observation-action value
        `NextQio[i, o'] = sum_a' X[i, o', a'] * Qioa[i, o', a']`
        instead of the next observation value `Vio[i, o']`.
        """
        Xisa = self.Xisa(X) if Xisa is None else Xisa
        Bios = self.fast_Bios(X) if Bios is None else Bios
        Qioa = self.Qioa(X, Bios=Bios, Xisa=Xisa) if Qioa is None else Qioa

        i = 0
        a = 1
        s = 2
        s_ = 3
        o = 4
        o_ = 5  # next observation
        j2k = list(range(6, 6 + self.N - 1))  # other agents
        b2d = list(range(6 + self.N - 1, 6 + self.N - 1 + self.N))  # all actions
        e2f = list(range(5 + 2 * self.N, 5 + 2 * self.N + self.N - 1))  # all other acts

        # On-policy expected next observation-action value (SARSA bootstrap):
        #   NextQio[i, o'] = sum_a' X[i, o', a'] * Qioa[i, o', a']
        # (the `a` label here is local to this einsum and reduced away)
        NextQio = jnp.einsum(
            Qioa, [i, o_, a], X, [i, o_, a], [i, o_], optimize=self.opti
        )

        sumsis = [[j2k[l], s, e2f[l]] for l in range(self.N - 1)]  # sum inds
        otherY = list(it.chain(*zip((self.N - 1) * [Xisa], sumsis)))

        args = (
            [self.Omega, [i] + j2k + [a] + b2d + e2f, Bios, [i, o, s]]
            + otherY
            + [self.T, [s] + b2d + [s_], self.O, [i, s_, o_], NextQio, [i, o_], [i, o, a]]
        )
        return jnp.einsum(*args, optimize=self.opti)
