"""Build llm_dynamics/llm_dynamics_notebook.ipynb — the source of truth for
the LLM cooperation-dynamics work: what we are doing, why, how it is
measured, what was run, and the results (read live from results/).

    JAX_PLATFORMS=cpu .venv-jaxmarl/bin/python llm_dynamics/build_notebook.py
Re-run after every experiment; the notebook re-reads results/ on execution.
"""
import os
import subprocess
import sys
import nbformat as nbf

HERE = os.path.dirname(os.path.abspath(__file__))
nb = nbf.v4.new_notebook(); C = []
def md(s): C.append(nbf.v4.new_markdown_cell(s))
def code(s): C.append(nbf.v4.new_code_cell(s))

md(r"""# Cooperation dynamics of LLM agents — source of truth

**Branch `donors-game-dynamics`, package `llm_dynamics/`.** This notebook is
regenerated by `llm_dynamics/build_notebook.py`; every table and figure below is
read from `llm_dynamics/results/` at execution time, so it always reflects the
latest runs. Narrative sections record the *decisions* (design, mappings,
deviations, caveats); code cells record the *evidence*.

## 0. What we are doing, in one paragraph

MARL-mixed studies the **dynamics of cooperation** — not just whether agents end up
cooperating, but the vector field of learning that carries them there — using
CRLD flow fields (pyCRLD) and, for learners without a closed-form flow (deep RL),
measured trajectories overlaid on the analytic flow of the reduced matrix game.
donorSim (branch `neurips-methodology`) trains LLMs with RL (verl GRPO; reward =
normalized donors-game payoff + HKB coordination term + CFE group term) on a
dyadic donors game against scripted strategies, and claims the training
**changes the LLM's dynamics**. Here we make that claim measurable: the same
phase portraits, with an LLM in the learner's seat — first the **base model**
(this notebook), then the RL-trained checkpoint on the same axes.
""")

md(r"""## 1. Background we build on

### 1.1 MARL-mixed methodology (this repo)
* State of the system = joint policy $X_i(a\mid s)$. A flow plot is a 2-D slice
  (agent-0 $P(C)$ vs agent-1 $P(C)$ in a chosen memory state); arrows are the
  deterministic CRLD learning step $\Delta X = \mathrm{step}(X)-X$
  (`pyCRLD.Utils.FlowPlot.plot_strategy_flow`, `use_RPEarrows=False`), with
  off-slice coordinates marginalized by Latin-hypercube sampling.
* Memory-$m$ games via `HistoryEmbedded(env, h=(m,)*(N+1))`, state count $(2^N)^m$.
* Observability regimes = row-stochastic observation-aliasing matrices
  (`scratch_repro/mem_obs_grids.py`: full / self / others / coop / def / blind).
* Learners with no analytic flow (JaxMARL deep RL, `jaxmarl_env/algo_phase.py`):
  grey CRLD arrows as theory, coloured measured paths as reality, **the deviation
  is the finding**.
* Paper findings we lean on: self-observability is load-bearing; memory enlarges
  the cooperative basin (memory-1 flow drains to defection, memory-2 has a (1,1)
  attractor); actor-critic is bistable, SARSA converges to an interior point.

### 1.2 donorSim `neurips-methodology`
* **Basic dyadic scenario** = the `direct_indirect` training rollout
  (`donor_sim/verl_integration/donor_game_interaction.py` +
  `donor_sim/game_helpers.py`): one LLM vs one scripted partner drawn from
  `OPPONENT_POOL` = {AllC .15, AllD .30, TFT .20, TF2T .20, Random .10, Grim .05};
  $b\sim U[3,6]$, $c/b\sim U[0.1,1.5]$, $w,q\in\{0,.25,.5,.75,1\}$, 3–8 rounds.
* Semantics: simultaneous moves ("If you COOPERATE: you receive 0, partner
  receives $b$; if you DEFECT: you receive $c$"); partner reacts to the model's
  *prior* rounds; **$w$** = probability the same partner returns next round
  (else a stranger arrives, per-partner history wiped); **$q$** = probability a
  reputation report about the partner is available.
* Training: verl GRPO (LoRA r=16, KL 0.001, 8 generations, per-turn credit),
  reward $r = \frac{\pi + c}{b+c} + \lambda_{tom}[4q\cos\phi + \tfrac{c}{b}\cos 2\phi] - \lambda_g\,\mathrm{CFE}$
  with HKB phase $\phi$ from a window-4 coordination signal; phase transition at
  $q = c/b$ (Nowak's indirect-reciprocity threshold). Released run on Qwen3-8B;
  a Qwen3-32B methodology checkpoint (`step_175`) exists.
* Eval stack already reads a continuous $p_{coop}$ from decision-token logprobs
  (`metastability_eval/harness/vllm_client.py`); branch `metastability-eval`
  holds the drift/dwell/Markov analyses.
""")

md(r"""## 2. The theory mapping: donors game → CRLD

| donorSim | CRLD (`llm_dynamics/donors_crld.py`) |
|---|---|
| payoffs $(b,c)$, both players donors | donation-game PD $(R,T,S,P)=(b-c,\;b,\;-c,\;0)$; on the training's normalized scale $\big(\tfrac{b}{b+c},1,0,\tfrac{c}{b+c}\big)$ (default) |
| $w$ — re-encounter probability | discount factor $\gamma=w$ (clamped to 0.99). Continuation probability *is* the discount factor of the repeated game; Nowak's $w>c/b$ is the discounted-game threshold |
| $q$ — reputation availability | observability blend $O = q\,O_{\text{full}} + (1-q)\,O_{\text{self}}$ — the partner's action is visible w.p. $q$, else only one's own |
| per-partner memory | `HistoryEmbedded(env, h=(m,m,m))` |
| set-strategy opponent | pinned policy $X_{opp}[s,a]$ (AllC/AllD/TFT/TF2T/Grim-$m$/WSLS, $\epsilon$-mixed); the learner's seat gets a **fixed-opponent flow field** |

Two backgrounds are therefore available for every $(b,c,w,q,m)$:
1. **two-agent CRLD flow** (both seats learning) in the *cooperation plane*
   $(P_{model}(C),\,P_{partner}(C))$ — the repo convention;
2. **fixed-opponent flow** in the *reciprocity plane*
   $\big(P(C\mid\text{sustained mutual }C),\;P(C\mid\text{own }C,\text{ partner }D)\big)$ —
   the theoretically matched background for "set strategy vs LLM".
""")

code(r"""# Live: the CRLD flow of the donors game at the sweep's parameters, both backgrounds.
import os, sys, json, glob, numpy as np, pandas as pd, matplotlib.pyplot as plt
ROOT = os.path.abspath(os.path.join(os.getcwd(), '..')) if os.path.basename(os.getcwd())=='llm_dynamics' else os.getcwd()
sys.path.insert(0, ROOT); os.chdir(ROOT)
from llm_dynamics import donors_crld as dc, plots
from pyCRLD.Utils import FlowPlot as fp
b, c, w, q, m = 4.0, 2.0, 0.75, 0.75, 1
memo = dc.donors_memo_env(b, c, memory=m, q=q); mae = dc.build_mae(memo, w=w, q=q)
fig, axs = plt.subplots(1, 2, figsize=(10, 4.6))
plots.crld_flow_background(axs[0], mae, dc.allc_state(memo))
axs[0].set_title(f'two-agent CRLD flow (b={b:g}, c/b={c/b:g}, γ=w={w}, q={q}, memory {m})', fontsize=9)
axs[0].set_xlabel('agent 0 P(C)'); axs[0].set_ylabel('agent 1 P(C)')
X_opp = dc.strategy_policy('tit_for_tat', memo)
XX, YY, dX, dY = dc.fixed_opponent_flow(mae, memo, X_opp, dc.uniform_state(memo,'c','c',m), dc.uniform_state(memo,'c','d',m), NrRandom=6)
mdx, mdy = dX.mean(-1), dY.mean(-1); L = np.sqrt(mdx**2+mdy**2)+1e-12
axs[1].quiver(XX, YY, mdx*np.sqrt(L)/L, mdy*np.sqrt(L)/L, color='0.6', angles='xy')
axs[1].set_title('fixed-opponent flow vs TFT (reciprocity plane)', fontsize=9)
axs[1].set_xlabel('P(C | sustained mutual C)'); axs[1].set_ylabel('P(C | own C, partner D)')
for a in axs: a.set_xlim(-.03,1.03); a.set_ylim(-.03,1.03)
plt.tight_layout(); plt.show()""")

md(r"""## 3. How the LLM is measured

* **Order parameter.** `p_cooperate` = renormalized COOPERATE-mass vs DEFECT-mass
  in the top-20 logprobs at the token after the *last* `DECISION:` marker
  (`llm_client.decision_probability`). It reads the distribution the sampler
  drew from; decoding is unchanged. Because the model writes a rationale before
  `DECISION:` (sampled at $T=0.6$), a single call's $p$ is near-binary — the
  stochasticity lives in the rationale — so means over seeds/rounds are needed.
* **Probes** (`policy_probe.py`): render the exact prompt for every memory-$m$
  history state ($4^m$ states) and read $p$ greedily → the LLM as a point
  $X[s]$ in CRLD policy space. Donors framing = conversational replay with forced
  `DECISION:` assistant turns; matrix framing = the stateless memory-$m$ prompt.
* **Play** (`donors_game.py`, `matrix_games.py`): full games vs a fixed
  strategy, per-round JSONL (`model_action`, `opp_action`, `p_cooperate`, HKB
  $\phi$, payoffs on both scales, swap events, visible state).
* **Portraits** (`plots.py`): cooperation-plane paths (sliding window 8) over the
  two-agent flow; reciprocity-plane stars (probes) + paths (windowed conditional
  frequencies) over the fixed-opponent flow; $q\times w$ heatmaps with the
  $q=c/b$ line.
* **Best-response regret** (`analysis.py`): oracle optimum vs the fixed strategy
  by dynamic programming over its state machine, per partner segment (swaps wipe
  the opponent's memory) — reported as *captured fraction* and regret/round,
  next to AllC/AllD baselines. "Against AllD the model should AllD" is
  `captured = 1.0`.

### 3.1 Fidelity to the training environment (deliberate choices)
* Donors prompts are byte-faithful to the `direct_indirect` rollout (rules,
  $w$/$q$ phrasing, $q$-gated reputation report, `/no_think`, round-result
  turns, swap text). Strategies, payoffs, HKB, parsing are vendored verbatim
  (`strategies.py`, from `game_helpers.py` @ merge-base `e665f87`).
* **Deviation:** `--swap-mode same` — a successor partner keeps the *same*
  strategy so the dyad stays strategy-controlled (`pool` reproduces training).
* **Addition:** `suspicious_tit_for_tat` (opens D, then mirrors) — not in the
  training pool; used so that half of the TFT games open with D.
* **Addition:** an LLM memory window for the donors framing (`--memories`):
  the rules prompt + only the last $m$ (assistant, round-result) turn pairs.
  `full` is the training setting.
* Matrix games are **stateless** per round with an explicit last-$m$ history
  block, so the LLM is genuinely a memory-$m$ policy on exactly the CRLD state
  space. Payoffs: PD (3,5,0,1), Chicken (3,5,1,0), Stag Hunt (5,3,0,1),
  Harmony (5,3,2,0) as $(R,T,S,P)$.
* Qwen3 thinking mode is **off** (`enable_thinking=False` + `/no_think`), the
  stage-1 training setting. Temperature 0.6 for play, 0 for probes.

### 3.2 Compute rule
**Everything GPU runs through SLURM** (`llm_dynamics/slurm/*.sbatch`), never on
`rnn`. Server: `serve_qwen32b.sbatch` (vllm-env, one A100-80GB, writes
`logs/vllm_endpoint.txt` + `.ready`). Clients are CPU jobs that wait on the
sentinel. `llm_dynamics/README.md` has the commands.
""")

md(r"""## 4. Experiment registry (base model = `Qwen/Qwen3-32B`, the pre-RL checkpoint)

| id | SLURM jobs | design | outputs |
|---|---|---|---|
| **v1** | server 1183776 / client 1183777 (2026-08-25, 1h13m) | donors: {TFT, AllD, AllC} × q,w ∈ {0,.5,1}, b=4, c/b=.5, 2 seeds × 20 rounds, full memory; probes m1 at 4 (w,q) corners + m2; matrix: 4 games × m ∈ {1,2} × {TFT, AllD} × 1 seed × 20 rounds; matrix probes m1,m2 | `results/qwen32b_base_donors_sweep/`, `results/qwen32b_base_matrix_sweep/`, `results/probes/qwen32b_base_*`, `results/qwen32b_base_reciprocity_tft.png` |
| **v2** | server 1183852 / client 1183853 (2026-08-25) | donors: {TFT, **suspicious TFT**, AllC, AllD, TF2T, Grim} × q,w ∈ {0,.5,1} × LLM memory {full,1,2,4} × 2 seeds × 20 rounds; matrix: same 6 strategies × 4 games × m ∈ {1,2,3,4,6} × 2 seeds; probes to m=3 both framings | `results/qwen32b_base_donors_v2/<strategy>/`, `results/qwen32b_base_matrix_v2/<strategy>/`, `results/qwen32b_base_v2_tables.md` |
| offline | — | `demo`: mock base-selfish vs mock trained-reciprocal through the identical code path | `results/demo_*` |

Memory ceiling: CRLD backgrounds stop at $m=3$ ($4^m$ states; `MAX_CRLD_MEMORY`);
the LLM prompt window is cheap and is swept to $m=6$ (probes to $m=3$: 64 calls
per framing; $m=4$ would be 256).
""")

md(r"""## 5. Results — base Qwen3-32B

### 5.1 Probed conditional policy (donors framing)""")
code(r"""def show_probes(pattern):
    rows = []
    for f in sorted(glob.glob(pattern)):
        p = json.load(open(f)); name = os.path.basename(f).replace('.json','')
        row = {'probe': name}
        row.update({k: v['p_cooperate'] for k, v in sorted(p['states'].items())})
        rows.append(row)
    return pd.DataFrame(rows).set_index('probe').round(2) if rows else 'pending'
display(show_probes('llm_dynamics/results/probes/qwen32b_base_donors_m1_*.json'))
display(show_probes('llm_dynamics/results/probes/qwen32b_base_donors_m2_*.json').T)""")
md(r"""State labels are `own/partner` initials, oldest → newest. Reading: `cc`=after
mutual cooperation, `cd`=after being suckered, `dc`=after exploiting, `dd`=after
mutual defection.""")

md(r"""### 5.2 Matrix-game probes (memory 1–3)""")
code(r"""for g in ['ipd','chicken','staghunt','harmony']:
    print(g); display(show_probes(f'llm_dynamics/results/probes/qwen32b_base_{g}_m1.json'))
display(show_probes('llm_dynamics/results/probes/qwen32b_base_*_m2.json').T)""")

md(r"""### 5.3 v1 sweep — cooperation rate and best-response regret""")
code(r"""from llm_dynamics import analysis
for d in ['llm_dynamics/results/qwen32b_base_donors_sweep', 'llm_dynamics/results/qwen32b_base_matrix_sweep']:
    if os.path.isdir(d):
        t = analysis.regret_table(d)
        df = pd.DataFrame([{**{'cell': ' '.join(k)}, **{kk: vv for kk, vv in v.items() if kk!='n'}} for k, v in t.items()]).set_index('cell')
        display(df.round(2))""")
code(r"""from IPython.display import Image, display as _d
for f in ['llm_dynamics/results/qwen32b_base_reciprocity_tft.png',
          'llm_dynamics/results/qwen32b_base_donors_sweep/heatmap_qwen3-32b-base_tit_for_tat.png',
          'llm_dynamics/results/qwen32b_base_donors_sweep/heatmap_qwen3-32b-base_always_defect.png',
          'llm_dynamics/results/qwen32b_base_donors_sweep/portrait_qwen3-32b-base_always_defect_q0.5_w0.5.png',
          'llm_dynamics/results/qwen32b_base_matrix_sweep/portrait_qwen3-32b-base_ipd_m1_tit_for_tat.png',
          'llm_dynamics/results/qwen32b_base_matrix_sweep/portrait_qwen3-32b-base_ipd_m2_tit_for_tat.png']:
    if os.path.exists(f): print(f); _d(Image(f, width=520))""")

md(r"""### 5.4 v2 — strategies (incl. suspicious TFT) × (w,q) × memory, and × games × memory

Each cell is **cooperation rate / captured fraction of the best-response payoff**.
(Reads `results/qwen32b_base_v2_tables.md`; shows *pending* until job 1183853 finishes.)""")
code(r"""from IPython.display import Markdown
f = 'llm_dynamics/results/qwen32b_base_v2_tables.md'
display(Markdown(open(f).read()) if os.path.exists(f) else Markdown('**v2 tables pending** (SLURM job 1183853)'))""")
code(r"""# v2 heatmaps per strategy x memory, when present
for f in sorted(glob.glob('llm_dynamics/results/qwen32b_base_donors_v2/*/heatmap_*.png')):
    print(f); _d(Image(f, width=420))""")

md(r"""## 6. Findings so far (base model) and what to compare against

* **Base Qwen3-32B is a near-deterministic hard tit-for-tat** in the donors
  framing: $P(C\mid cc)=1$, $P(C\mid dc)=1$, $P(C\mid cd)=0$ at every $(w,q)$
  corner (memory 1). In the reciprocity plane it sits at the (1, 0) corner, where
  the fixed-opponent CRLD flow vs TFT points *away* (toward forgiveness).
* **$q$ acts through the reputation report, $w$ barely acts.** Opening $P(C)$
  vs AllD is 0.00 whenever a report is guaranteed ($q=1$) and 1.00 at $q=0,w\ge.5$;
  with one-shot strangers ($w=0$) and no information it hedges (0.50 vs AllC).
  After round 1 the last move dominates and $(w,q)$ stop mattering.
* **Regret view:** ≈1.0 of optimum vs AllD and vs TFT with a stable partner
  ($w=1$, 0.98); leaves a third on the table vs AllC (never exploits, 0.67) and
  vs one-shot strangers (cooperates where the oracle defects).
* **Memory matters exactly as in the paper:** PD vs TFT at memory 1 falls into
  the TFT echo cycle (coop 0.35, captured 0.69); memory 2 escapes (0.95 / 1.00).
* **Payoff-structure blindness:** the memory-1 probed policy is identical across
  PD, Chicken and Stag Hunt (`cc=1, cd=0, dc=1, dd=1`), and against AllD in
  Chicken/Harmony — where the best response is to *cooperate* — it retaliates
  and captures only 25–45%.

**For the RL-trained checkpoint** the cells to watch are: $P(C\mid cd)$
(forgiveness — does training move the star off the (1,0) corner?), the AllC
column (exploitation), the $w=0$ column (one-shot strangers), and the
Chicken/Harmony-vs-AllD cells (does it learn the game or stay a reflex
reciprocator?). Protocol: serve the merged checkpoint with
`serve_qwen32b.sbatch` (change model path / `--served-model-name`), then
`TAG=qwen32b_trained MODEL=<name> sbatch llm_dynamics/slurm/run_suite_v2.sbatch`,
then `reciprocity-figure --probes <base> <trained>`.

## 7. Caveats
* Two seeds per cell, 20 rounds: coarse; a $q=0$ column has identical prompts
  across partner rows, so differences there are sampling noise.
* $c/b=0.5$ fixed, so Nowak's thresholds sit on the middle grid value; a $c/b$
  sweep is needed to test threshold-tracking vs report-text-following.
* Probes are greedy at a fixed mid-game round; play is sampled across the whole
  game (end-game effects included).
* The played path in the reciprocity plane needs the `cd` state to occur; vs TFT
  it never does, so that coordinate stays at its 0.5 default (use the probe star).
* `grim_trigger` is pinned as its memory-$m$ truncation; suspicious TFT has the
  same state-space policy as TFT (the opening move is not a state).
""")

nb["cells"] = C
out = os.path.join(HERE, "llm_dynamics_notebook.ipynb")
with open(out, "w") as f:
    nbf.write(nb, f)
print("wrote", out)
if "--execute" in sys.argv:
    subprocess.run([sys.executable, "-m", "nbconvert", "--to", "notebook", "--execute",
                    "--inplace", "--ExecutePreprocessor.timeout=1800", out], check=True)
    print("executed", out)
